=== redpanda-data-blog/demos-iceberg-topics/demos/demo3/telemetry-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "level": {
      "type": "object",
      "properties": {
        "episode": {
          "type": "integer"
        },
        "level": {
          "type": "integer"
        },
        "difficulty": {
          "type": "integer"
        }
      },
      "required": ["episode", "level", "difficulty"]
    },
    "weapon_type": {
      "type": "integer"
    },
    "armor_type": {
      "type": "integer"
    },
    "health": {
      "type": "integer"
    },
    "damage": {
      "type": "integer"
    },
    "card": {
      "type": "integer"
    },
    "armor": {
      "type": "integer"
    },
    "counter": {
      "type": "integer"
    },
    "session": {
      "type": "string"
    },
    "type": {
      "type": "string"
    },
    "frame": {
      "type": "object",
      "properties": {
        "millis": {
          "type": "integer"
        },
        "tic": {
          "type": "integer"
        }
      },
      "required": ["millis", "tic"]
    },
    "actor": {
      "type": "object",
      "properties": {
        "position": {
          "type": "object",
          "properties": {
            "x": {
              "type": "integer"
            },
            "y": {
              "type": "integer"
            },
            "z": {
              "type": "integer"
            },
            "angle": {
              "type": "integer"
            },
            "subsector": {
              "type": "integer"
            }
          },
          "required": ["x", "y", "z", "angle", "subsector"]
        },
        "type": {
          "type": "string"
        },
        "health": {
          "type": "integer"
        },
        "armor": {
          "type": "integer"
        },
        "id": {
          "type": "integer"
        }
      },
      "required": ["position", "type", "health", "armor", "id"]
    },
    "target": {
      "type": "object",
      "properties": {
        "position": {
          "type": "object",
          "properties": {
            "x": {
              "type": "integer"
            },
            "y": {
              "type": "integer"
            },
            "z": {
              "type": "integer"
            },
            "angle": {
              "type": "integer"
            },
            "subsector": {
              "type": "integer"
            }
          },
          "required": ["x", "y", "z", "angle", "subsector"]
        },
        "type": {
          "type": "string"
        },
        "health": {
          "type": "integer"
        },
        "armor": {
          "type": "integer"
        },
        "id": {
          "type": "integer"
        }
      },
      "required": ["position", "type", "health", "armor", "id"]
    }
  }
}

=== redpanda-data-blog/demos-iceberg-topics/demos/demo3/samples/pickup_card.json
{
  "card": 1,
  "counter": 4841,
  "session": "7843f99368399d1987339790",
  "type": "pickup_card",
  "frame": {
    "millis": 44115,
    "tic": 1544
  },
  "actor": {
    "position": {
      "x": 47668403,
      "y": 54674404,
      "z": 3670016,
      "angle": 2516582400,
      "subsector": 5815513200
    },
    "type": "player",
    "health": 90,
    "armor": 85,
    "id": 5815639608
  }
}

=== redpanda-data-blog/demos-iceberg-topics/demos/demo3/samples/enter_subsector.json
{
  "counter": 13161,
  "session": "7843f99368399d1987339790",
  "type": "enter_subsector",
  "frame": {
    "millis": 97259,
    "tic": 3404
  },
  "actor": {
    "position": {
      "x": -11779917,
      "y": -211381952,
      "z": 8388608,
      "angle": 2035810304,
      "subsector": 5816187728
    },
    "type": "player",
    "health": 100,
    "armor": 100,
    "id": 5816267936
  }
}

=== redpanda-data-blog/demos-iceberg-topics/demos/demo3/samples/move.json
{
  "counter": 13811,
  "session": "7843f99368399d1987339790",
  "type": "move",
  "frame": {
    "millis": 107400,
    "tic": 3759
  },
  "actor": {
    "position": {
      "x": 96397684,
      "y": -161719438,
      "z": 0,
      "angle": 4191682560,
      "subsector": 5816186784
    },
    "type": "player",
    "health": 100,
    "armor": 100,
    "id": 5816267936
  }
}

=== redpanda-data-blog/demos-iceberg-topics/demos/demo3/samples/pickup_armor.json
{
  "armor_type": 1,
  "counter": 13123,
  "session": "7843f99368399d1987339790",
  "type": "pickup_armor",
  "frame": {
    "millis": 96686,
    "tic": 3384
  },
  "actor": {
    "position": {
      "x": -12271633,
      "y": -211331781,
      "z": 8388608,
      "angle": 2119696384,
      "subsector": 5816187808
    },
    "type": "player",
    "health": 100,
    "armor": 100,
    "id": 5816267936
  }
}

=== redpanda-data-blog/demos-iceberg-topics/demos/demo3/samples/start-level.json
{
  "level": {
    "episode": 1,
    "level": 5,
    "difficulty": 2
  },
  "counter": 0,
  "session": "736e492a4461b02e7264892b",
  "type": "start_level",
  "frame": {
    "millis": 5462,
    "tic": 191
  },
  "actor": {
    "position": {
      "x": -14680064,
      "y": -40894464,
      "z": 0,
      "angle": 1073741824,
      "subsector": 5261842056
    },
    "type": "player",
    "health": 100,
    "armor": 0,
    "id": 5261970112
  }
}

=== redpanda-data-blog/demos-iceberg-topics/demos/demo3/samples/pickup_weapon.json
{
  "weapon_type": 4,
  "counter": 6978,
  "session": "7843f99368399d1987339790",
  "type": "pickup_weapon",
  "frame": {
    "millis": 56458,
    "tic": 1976
  },
  "actor": {
    "position": {
      "x": 87031425,
      "y": 5572949,
      "z": -1048576,
      "angle": 3154116608,
      "subsector": 5815512720
    },
    "type": "player",
    "health": 82,
    "armor": 200,
    "id": 5815639608
  }
}

=== redpanda-data-blog/demos-iceberg-topics/demos/demo3/samples/health_bonus.json
{
  "health": 83,
  "counter": 2839,
  "session": "7843f99368399d1987339790",
  "type": "health_bonus",
  "frame": {
    "millis": 30944,
    "tic": 1083
  },
  "actor": {
    "position": {
      "x": 60814666,
      "y": 21292704,
      "z": 0,
      "angle": 1090519040,
      "subsector": 5815513040
    },
    "type": "player",
    "health": 83,
    "armor": 94,
    "id": 5815639608
  }
}

=== redpanda-data-blog/demos-iceberg-topics/demos/demo3/samples/armor-bonus.json
{
  "armor": 2,
  "counter": 13066,
  "session": "7843f99368399d1987339790",
  "type": "armor_bonus",
  "frame": {
    "millis": 95859,
    "tic": 3355
  },
  "actor": {
    "position": {
      "x": 347498,
      "y": -211822566,
      "z": 6815744,
      "angle": 2119696384,
      "subsector": 5816188096
    },
    "type": "player",
    "health": 100,
    "armor": 2,
    "id": 5816267936
  }
}
